name: Execute Python Scripts

on:
  push:
    branches:
      - main
      - devel

jobs:
  execute-scripts:
    name: Execute Python Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Clone cssrlib repository
        run: git clone -b ${{ github.ref }} https://github.com/${{ github.actor }}/cssrlib.git
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Python scripts
        run: |
          export PYTHONPATH="./cssrlib/src:$PATHONPATH"
          cd ./samples
          for file in $(find . -name "*.py"); do
            echo "Execute $file"
            echo 
            python "$file"
            echo "#"
            echo "# ...done!"
            echo "#"
            echo
          done
