name: Execute Python Scripts

on:
  push:
    branches:
      - main
      - devel

jobs:
  execute-scripts:
    name: Execute Python Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cssrlib-data repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies from cssrlib-data repository
        run: pip install -r requirements.txt

      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::$(basename $GITHUB_REF)"

      - name: Clone cssrlib repository
        run: git clone -b ${{ steps.get_branch_name.outputs.branch_name }} https://github.com/${{ github.actor }}/cssrlib.git
        
      - name: Install dependencies from cssrlib repository
        run: |
          cd cssrlib
          pip install -r requirements.txt
 
      - name: Execute Python scripts
        run: |
          export PYTHONPATH="../cssrlib/src:$PATHONPATH"
          cd ./samples
          for file in $(find . -name "*.py"); do
            if [ "$file" == "./test_ppprtcm.py" ]; then continue; fi
            if [ "$file" == "./test_sisre_mdc.py" ]; then continue; fi
            echo "# Execute $file"
            echo "#"
            python "$file" > /dev/null
            echo "#"
            echo "# ...done!"
            echo "#"
            echo
          done
