name: Execute Python Scripts

on:
  push:
    branches:
      - main
      - devel

jobs:
  execute-scripts:
    name: Execute Python Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any dependencies, adjust as needed

      - name: Execute Python scripts
        run: |
          cd ./samples
          for file in $(find . -name "*.py"); do
            echo "Execute $file"
            echo 
            python "$file"
            echo "#"
            echo "# ...done!"
            echo "#"
            echo
          done
